package com.adventofcode.aoc2025;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class Day07Test {

    private static final String PUZZLE_EXAMPLE = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """;

    @Test
    void puzzleExample_part1_lf() {
        Day07 day07 = new Day07();
        Day.Answers answers = day07.solve(PUZZLE_EXAMPLE);
        Assertions.assertEquals(21L, answers.part1());
        Assertions.assertNull(answers.part2());
    }

    @Test
    void puzzleExample_part1_crlf() {
        Day07 day07 = new Day07();
        Day.Answers answers = day07.solve(PUZZLE_EXAMPLE.replace("\n", "\r\n"));
        Assertions.assertEquals(21L, answers.part1());
        Assertions.assertNull(answers.part2());
    }
}

